CATEGORY_GROUPS = {
    "Locations": [
        "Bulletin Board",
        "Camp",
        "Fast Travel",
        "Point of Interest",
        "Safehouse",
        "Transition",
        "Traversal",
        "Vendor",
    ],
    "Collectibles": [
        "Adam's Clothes",
        "Box",
        "Can",
        "Data Bank",
        "Drone Appearance",
        "Earrings",
        "Face Decoration",
        "Fish",
        "Hairstyle",
        "Lily's Clothes",
        "Lost Song",
        "Memory Stick",
        "Nano Suit",
        "Passcode",
        "Photo Spot",
        "Stellar Tear",
    ],
    "Equipment": [
        "Beta Core",
        "Body Core",
        "Drone Upgrade Module",
        "Exospine",
        "Gear",
        "Omnibolt",
        "Tumbler Expansion Module",
        "Weapon Core",
    ],
    "Missions": ["Bulletin Board Request", "Main Quest", "Mission Item", "Side Quest"],
    "Enemies": ["Boss", "Naytiba"],
    "Other": ["Easter Egg", "Miscellaneous"],
}

CATEGORY_COLORS = {
    "Bulletin Board": "#64b5f6",
    "Camp": "#39d98a",
    "Fast Travel": "#2ec5ff",
    "Point of Interest": "#d2a8ff",
    "Safehouse": "#66bb6a",
    "Transition": "#90a4ae",
    "Traversal": "#ffd166",
    "Vendor": "#ba68c8",
    "Adam's Clothes": "#ec407a",
    "Box": "#f59e0b",
    "Can": "#84cc16",
    "Data Bank": "#f472b6",
    "Drone Appearance": "#26c6da",
    "Earrings": "#ffca28",
    "Face Decoration": "#ab47bc",
    "Fish": "#4fc3f7",
    "Hairstyle": "#8d6e63",
    "Lily's Clothes": "#ffa726",
    "Lost Song": "#26a69a",
    "Memory Stick": "#60a5fa",
    "Nano Suit": "#fb7185",
    "Passcode": "#e879f9",
    "Photo Spot": "#7e57c2",
    "Stellar Tear": "#29b6f6",
    "Beta Core": "#22d3ee",
    "Body Core": "#14b8a6",
    "Drone Upgrade Module": "#a3e635",
    "Exospine": "#ff8a65",
    "Gear": "#facc15",
    "Omnibolt": "#ff7043",
    "Tumbler Expansion Module": "#4db6ac",
    "Weapon Core": "#ef4444",
    "Bulletin Board Request": "#4dd0e1",
    "Main Quest": "#ff5d73",
    "Mission Item": "#93c5fd",
    "Side Quest": "#c084fc",
    "Boss": "#dc2626",
    "Naytiba": "#f97316",
    "Easter Egg": "#f43f5e",
    "Miscellaneous": "#9ca3af",
}

MAP_DEFINITIONS = [
    {"slug": "eidos-7", "name": "Eidos 7"},
    {"slug": "xion-city", "name": "Xion City"},
    {"slug": "wasteland", "name": "Wasteland"},
    {"slug": "altess-levoire", "name": "Altess Levoire"},
    {"slug": "matrix-11", "name": "Matrix 11"},
    {"slug": "great-desert", "name": "Great Desert"},
    {"slug": "abyss-levoire", "name": "Abyss Levoire"},
    {"slug": "eidos-9", "name": "Eidos 9"},
    {"slug": "spire-4", "name": "Spire 4"},
]

MAP_CATEGORY_COUNTS = {
    "eidos-7": {
        "Camp": 14,
        "Fast Travel": 1,
        "Point of Interest": 9,
        "Traversal": 47,
        "Box": 35,
        "Can": 3,
        "Data Bank": 7,
        "Drone Appearance": 1,
        "Earrings": 2,
        "Fish": 2,
        "Memory Stick": 34,
        "Nano Suit": 3,
        "Passcode": 6,
        "Beta Core": 5,
        "Body Core": 5,
        "Drone Upgrade Module": 3,
        "Exospine": 3,
        "Gear": 10,
        "Omnibolt": 4,
        "Tumbler Expansion Module": 4,
        "Weapon Core": 3,
        "Main Quest": 1,
        "Mission Item": 18,
        "Side Quest": 2,
        "Boss": 3,
        "Naytiba": 115,
        "Easter Egg": 2,
        "Miscellaneous": 28,
    },
    "xion-city": {
        "Bulletin Board": 1,
        "Camp": 1,
        "Fast Travel": 4,
        "Point of Interest": 4,
        "Safehouse": 1,
        "Transition": 4,
        "Traversal": 2,
        "Vendor": 5,
        "Adam's Clothes": 1,
        "Box": 10,
        "Can": 8,
        "Data Bank": 49,
        "Drone Appearance": 1,
        "Earrings": 11,
        "Face Decoration": 1,
        "Fish": 1,
        "Hairstyle": 13,
        "Lost Song": 1,
        "Memory Stick": 5,
        "Nano Suit": 23,
        "Passcode": 1,
        "Photo Spot": 11,
        "Body Core": 1,
        "Drone Upgrade Module": 1,
        "Gear": 19,
        "Omnibolt": 2,
        "Weapon Core": 1,
        "Bulletin Board Request": 32,
        "Main Quest": 5,
        "Mission Item": 2,
        "Side Quest": 26,
        "Boss": 1,
        "Miscellaneous": 17,
    },
    "wasteland": {
        "Bulletin Board": 1,
        "Camp": 13,
        "Fast Travel": 6,
        "Point of Interest": 4,
        "Safehouse": 1,
        "Transition": 2,
        "Traversal": 21,
        "Vendor": 3,
        "Adam's Clothes": 2,
        "Box": 36,
        "Can": 15,
        "Data Bank": 16,
        "Drone Appearance": 1,
        "Face Decoration": 15,
        "Fish": 2,
        "Hairstyle": 8,
        "Lily's Clothes": 2,
        "Lost Song": 4,
        "Memory Stick": 37,
        "Nano Suit": 15,
        "Passcode": 4,
        "Photo Spot": 10,
        "Stellar Tear": 8,
        "Beta Core": 4,
        "Body Core": 3,
        "Drone Upgrade Module": 6,
        "Exospine": 3,
        "Gear": 10,
        "Omnibolt": 6,
        "Tumbler Expansion Module": 2,
        "Weapon Core": 5,
        "Bulletin Board Request": 5,
        "Main Quest": 4,
        "Mission Item": 11,
        "Side Quest": 4,
        "Boss": 8,
        "Naytiba": 138,
        "Miscellaneous": 40,
    },
    "altess-levoire": {
        "Camp": 5,
        "Point of Interest": 6,
        "Transition": 1,
        "Traversal": 2,
        "Box": 7,
        "Data Bank": 6,
        "Passcode": 1,
        "Drone Upgrade Module": 2,
        "Gear": 2,
        "Tumbler Expansion Module": 1,
        "Weapon Core": 1,
        "Mission Item": 1,
        "Boss": 1,
        "Naytiba": 21,
        "Easter Egg": 1,
        "Miscellaneous": 24,
    },
    "matrix-11": {
        "Camp": 11,
        "Fast Travel": 1,
        "Point of Interest": 5,
        "Transition": 1,
        "Traversal": 5,
        "Adam's Clothes": 1,
        "Box": 33,
        "Can": 3,
        "Data Bank": 6,
        "Earrings": 1,
        "Fish": 1,
        "Memory Stick": 23,
        "Nano Suit": 4,
        "Passcode": 4,
        "Beta Core": 4,
        "Body Core": 4,
        "Drone Upgrade Module": 6,
        "Exospine": 3,
        "Gear": 11,
        "Omnibolt": 5,
        "Tumbler Expansion Module": 4,
        "Weapon Core": 3,
        "Main Quest": 1,
        "Mission Item": 6,
        "Boss": 3,
        "Naytiba": 47,
        "Easter Egg": 1,
        "Miscellaneous": 15,
    },
    "great-desert": {
        "Camp": 18,
        "Fast Travel": 6,
        "Point of Interest": 11,
        "Safehouse": 2,
        "Transition": 3,
        "Traversal": 45,
        "Vendor": 1,
        "Box": 49,
        "Can": 16,
        "Data Bank": 19,
        "Face Decoration": 1,
        "Fish": 1,
        "Lily's Clothes": 1,
        "Lost Song": 4,
        "Memory Stick": 52,
        "Nano Suit": 8,
        "Passcode": 5,
        "Photo Spot": 10,
        "Stellar Tear": 7,
        "Beta Core": 3,
        "Body Core": 3,
        "Drone Upgrade Module": 4,
        "Exospine": 2,
        "Gear": 8,
        "Omnibolt": 6,
        "Tumbler Expansion Module": 1,
        "Weapon Core": 3,
        "Main Quest": 1,
        "Mission Item": 9,
        "Side Quest": 3,
        "Boss": 4,
        "Naytiba": 152,
        "Miscellaneous": 21,
    },
    "abyss-levoire": {
        "Camp": 7,
        "Point of Interest": 4,
        "Transition": 1,
        "Traversal": 18,
        "Box": 10,
        "Data Bank": 5,
        "Nano Suit": 1,
        "Drone Upgrade Module": 2,
        "Gear": 2,
        "Tumbler Expansion Module": 1,
        "Weapon Core": 1,
        "Mission Item": 1,
        "Boss": 1,
        "Naytiba": 36,
        "Miscellaneous": 11,
    },
    "eidos-9": {
        "Camp": 6,
        "Point of Interest": 4,
        "Safehouse": 2,
        "Traversal": 14,
        "Box": 24,
        "Data Bank": 4,
        "Fish": 1,
        "Memory Stick": 7,
        "Nano Suit": 3,
        "Drone Upgrade Module": 2,
        "Gear": 3,
        "Omnibolt": 1,
        "Weapon Core": 1,
        "Main Quest": 1,
        "Boss": 1,
        "Naytiba": 36,
    },
    "spire-4": {
        "Camp": 14,
        "Traversal": 26,
        "Box": 32,
        "Can": 4,
        "Data Bank": 2,
        "Drone Appearance": 1,
        "Earrings": 1,
        "Face Decoration": 1,
        "Memory Stick": 28,
        "Nano Suit": 3,
        "Passcode": 2,
        "Beta Core": 4,
        "Body Core": 4,
        "Drone Upgrade Module": 4,
        "Exospine": 1,
        "Gear": 12,
        "Omnibolt": 6,
        "Tumbler Expansion Module": 3,
        "Weapon Core": 3,
        "Main Quest": 1,
        "Boss": 5,
        "Naytiba": 57,
        "Miscellaneous": 17,
    },
}


def _seed_for_slug(slug: str) -> int:
    return sum(ord(char) for char in slug)


def _build_points(slug: str, counts: dict[str, int]) -> list[dict]:
    seed = _seed_for_slug(slug)
    points: list[dict] = []
    marker_index = 0

    for category in sorted(counts.keys()):
        category_count = counts[category]
        for category_index in range(category_count):
            marker_index += 1
            # Deterministic placeholder layout in 0..100 map space.
            x = 4 + ((marker_index * 13 + seed + category_index * 3) % 92)
            y = 4 + ((marker_index * 29 + seed * 2 + category_index * 5) % 92)
            points.append(
                {
                    "id": f"{slug}-{category}-{category_index + 1}",
                    "name": f"{category} #{category_index + 1}",
                    "type": category,
                    "x": x,
                    "y": y,
                    "note": "Auto-generated placeholder marker. Replace with exact coordinates.",
                }
            )
    return points


MAPS = [
    {
        "slug": definition["slug"],
        "name": definition["name"],
        "points": _build_points(definition["slug"], MAP_CATEGORY_COUNTS[definition["slug"]]),
        "categoryCounts": MAP_CATEGORY_COUNTS[definition["slug"]],
    }
    for definition in MAP_DEFINITIONS
]
